#ifndef MILIHEADER_H
#define MILIHEADER_H
enum SIDE { RED, BLUE, UNDETERMINED };
constexpr int HOR_ANCHOR[] = {4, 91, 179, 267, 354};
constexpr int VER_ANCHOR[] = {7,   48,  91,  133, 175, 218,
                              354, 395, 438, 481, 523, 566};
enum PIECE_TYPE {
    BANNAR,
    MINE,
    BOMB,
    COMM,
    JUN,
    SHI,
    LV,
    TUAN,
    YING,
    LIAN,
    PAI,
    SOLDIER,
    EMPTY,
    UNPROTECTED_BANNAR
};
constexpr char TYPE_NAME[][10] = {"Bannar", "Mine",    "Bomb", "Comm", "Jun",
                                  "Shi",    "Lv",      "Tuan", "Ying", "Lian",
                                  "Pai",    "Soldier", "Empty"};
constexpr char TYPE_NAME_CHN[][20]={"军旗","地雷","炸弹","司令","军长","师长","旅长","团长","营长","连长","排长","工兵","空棋","地雷"};
constexpr int XINGYING[][2] = {{2, 1}, {2, 3}, {3, 2}, {4, 1}, {4, 3},
                               {7, 1}, {7, 3}, {8, 2}, {9, 1}, {9, 3}};
enum PIECE_CLASH_RESULT{ILLEGAL_CLASH,WIN,LOSE,BOTH_DIE};
constexpr PIECE_CLASH_RESULT WIN_CHART[14][14]={{ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH},
                                                {ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH},
                                                {ILLEGAL_CLASH,ILLEGAL_CLASH,BOTH_DIE,BOTH_DIE,BOTH_DIE,BOTH_DIE,BOTH_DIE,BOTH_DIE,BOTH_DIE,BOTH_DIE,BOTH_DIE,BOTH_DIE,WIN,WIN},
                                                {ILLEGAL_CLASH,ILLEGAL_CLASH,BOTH_DIE,WIN,WIN,WIN,WIN,WIN,WIN,WIN,WIN,WIN,WIN},
                                                {ILLEGAL_CLASH,ILLEGAL_CLASH,BOTH_DIE,LOSE,BOTH_DIE,WIN,WIN,WIN,WIN,WIN,WIN,WIN,WIN,WIN},
                                                {ILLEGAL_CLASH,ILLEGAL_CLASH,BOTH_DIE,LOSE,LOSE,BOTH_DIE,WIN,WIN,WIN,WIN,WIN,WIN,WIN,WIN},
                                                {ILLEGAL_CLASH,ILLEGAL_CLASH,BOTH_DIE,LOSE,LOSE,LOSE,BOTH_DIE,WIN,WIN,WIN,WIN,WIN,WIN,WIN},//LV
                                                {ILLEGAL_CLASH,ILLEGAL_CLASH,BOTH_DIE,LOSE,LOSE,LOSE,LOSE,BOTH_DIE,WIN,WIN,WIN,WIN,WIN,WIN},
                                                {ILLEGAL_CLASH,ILLEGAL_CLASH,BOTH_DIE,LOSE,LOSE,LOSE,LOSE,LOSE,BOTH_DIE,WIN,WIN,WIN,WIN,WIN},
                                                {ILLEGAL_CLASH,ILLEGAL_CLASH,BOTH_DIE,LOSE,LOSE,LOSE,LOSE,LOSE,LOSE,BOTH_DIE,WIN,WIN,WIN,WIN},
                                                {ILLEGAL_CLASH,ILLEGAL_CLASH,BOTH_DIE,LOSE,LOSE,LOSE,LOSE,LOSE,LOSE,LOSE,BOTH_DIE,WIN,WIN,WIN},
                                                {ILLEGAL_CLASH,WIN,BOTH_DIE,LOSE,LOSE,LOSE,LOSE,LOSE,LOSE,LOSE,LOSE,BOTH_DIE,WIN,WIN},//SOLDIER
                                                {ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH},
                                                {ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH,ILLEGAL_CLASH}};
#endif  // MILIHEADER_H
